spring:
  cloud:
    zookeeper:
      connect-string: zoo1:2181,zoo2:2181,zoo3:2181
      discovery:
        enabled: true
        root: /scz
        register: false
      dependencies:
        zkservice1:
          path: /zkservice1
          loadBalancerType: ROUND_ROBIN
          required: false
